package responses

const INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
const FAILED_TO_CREATE_AUTH_TOKENS = "FAILED_TO_CREATE_AUTH_TOKENS"
const FAILED_TO_HASH_PASSWORD = "FAILED TO HASH PASSWORD"
const FAILED_TO_CREATE_USER = "FAILED TO CREATE USER"

const USER_ALREADY_EXISTS = "USER ALREADY EXISTS"
const FAILED_TO_MARSHAL = "FAILED_TO_MARSHAL"
const USER_DOES_NOT_EXISTS = "USER DOES NOT EXISTS"
const REQUIRED_FIELDS_ARE_EMPTY = "REQUIRED FIELDS ARE EMPTY"
const SLUG_ALREADY_EXISTS = "SLUG ALREADY EXISTS "
const UNAUTHORIZED = "UNAUTHORIZED"
const INVALID_TOKEN = "INVALID TOKEN"
