package responses

const INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
const FAILED_TO_CREATE_AUTH_TOKENS = "FAILED_TO_CREATE_AUTH_TOKENS"
const FAILED_TO_HASH_PASSWORD = "FAILED TO HASH PASSWORD"
const FAILED_TO_CREATE_USER = "FAILED TO CREATE USER"

const USER_ALREADY_EXISTS = "USER ALREADY EXISTS"
