services:
  postgres:
    image: postgres:latest
    container_name: q_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=q_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=q_task
  
  redis:
    image: redis:latest
    container_name: q_redis
    environment:
      - REDIS_URI=redis:6379
    ports:
      - 6379:6379
  
  q_app:
    container_name: q_app
    build: .
    ports:
      - 7788:7789
    restart: on-failure
    depends_on:
      - postgres
      - redis
    env_file: .env